### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by esud1** [UdeM-LBIT/CoreTracker#4]
Hi! 

I am interested to use the CoreTracker program, but encountered some problems during the installation. 
I have followed the instruction for conda installation but was given this error message: 

```
Fetching package metadata: ..........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - coretracker
  - mkl_fft (target=mkl_fft-1.0.15-py27ha843d7b_0.tar.bz2) -> numpy >=1.11.3,<2.0a0
  - mkl_random (target=mkl_random-1.1.0-py27hd6b4f25_0.tar.bz2) -> numpy >=1.14.6,<2.0a0
Use "conda info <package>" to see the dependencies for each package.
```
I have tried to reinstall the numpy and scipy as recommended, but the problem still persist. 
Do you know how to troubleshoot this? 

Thanks!

**Comment by maclandrol** [comment]
Hi @esud1, I have not encountered this error before. Did you follow the fresh installation using a new conda environment or tried to install in an existing one ?

**Comment by esud1** [comment]
Hi @maclandrol 

I used a new conda environment. 

I have also tried to install via pip installation, but there seems to be some conflict with the dependencies, as some no longer support python 2.x.

**Comment by maclandrol** [comment]
You should use the provided env.yml file in that case. It contains the specific version of each package.  Start with a fresh python 2.7  conda environment then update it with the provided yaml file. Let me know how it goes and if you need help for any step.

**Comment by esud1** [comment]
Hi @maclandrol 

Many thanks for your help! 
I have tried following the env.yml file and things seem to work out, but when I tried to call coretracker, it returns ValueError. 

```
conda env create -f env.yml
Fetching package metadata ...................
Solving package specifications: .
Requirement already satisfied (use --upgrade to upgrade): backports.shutil-get-terminal-size==1.0.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Collecting biopython==1.69
Collecting cairocffi==0.8.0
Collecting cairosvg==1.0.22
Collecting cffi==1.10.0
  Using cached https://files.pythonhosted.org/packages/50/85/d74d06ac09fc2deb3d9bd6d6aca4ca13d82b8118c04494cd0e84fcd81624/cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cssselect==1.0.1
  Using cached https://files.pythonhosted.org/packages/1d/e5/f1d410192e34b1034dba7804de5dbcdece20a883c445ad661e5ea8226b42/cssselect-1.0.1-py2.py3-none-any.whl
Collecting cycler==0.10.0
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): decorator==4.0.10 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Collecting ete3==3.0.0b35
Collecting functools32==3.2.3.post2
Collecting html5lib==0.999999999
  Using cached https://files.pythonhosted.org/packages/f7/71/a96f36d34394bcfff9fb54bfe0aa72cc5b4ff2f803e5728645aef38f7aee/html5lib-0.999999999-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils==0.2.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Collecting lxml==3.7.3
  Using cached https://files.pythonhosted.org/packages/cd/73/2bac3a3c0487fedd64d829d614cb38cecf244fcf34e1f140b9892a10ed0e/lxml-3.7.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting matplotlib==2.0.2
  Using cached https://files.pythonhosted.org/packages/2c/69/362c0a5eca37225c7d451e6c57f07c4fee85a5b6cb3aedf16fe649f411ea/matplotlib-2.0.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting numpy==1.12.1
  Using cached https://files.pythonhosted.org/packages/f9/d5/f24f86b51298f171826a398efdd64b5214b687a28a2f05ff736b1505b1b2/numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pandas==0.16.0
Requirement already satisfied (use --upgrade to upgrade): path.py==0.0.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pathlib2==2.1.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pexpect==4.0.1 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pickleshare==0.7.2 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Collecting pip==9.0.1
  Using cached https://files.pythonhosted.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): ptyprocess==0.5.1 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Collecting pycparser==2.17
Collecting pyparsing==2.2.0
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting pyphen==0.9.4
  Using cached https://files.pythonhosted.org/packages/dd/c4/74859f895e2361d92cfbb6208ea7afd06c2f1f05c491da71cbd7ce3887be/Pyphen-0.9.4-py2.py3-none-any.whl
Collecting python-dateutil==2.6.0
  Using cached https://files.pythonhosted.org/packages/40/8b/275015d7a9ec293cf1bbf55433258fbc9d0711890a7f6dc538bac7b86bce/python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting pytz==2017.2
  Using cached https://files.pythonhosted.org/packages/55/62/e7cd0e15b76062d298413f14bb4ec3cd8568a22d274427f9c3c7286969f4/pytz-2017.2-py2.py3-none-any.whl
Collecting pyyaml==3.12
Collecting scikit-learn==0.17
Collecting scipy==0.19.0
  Using cached https://files.pythonhosted.org/packages/eb/7e/27b3b9e26cb64e081799546a756059baf285eb886a771e9d26743876ccbb/scipy-0.19.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting seaborn==0.7.1
Requirement already satisfied (use --upgrade to upgrade): setuptools==23.0.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): simplegeneric==0.8.1 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Collecting subprocess32==3.2.7
Collecting tinycss==0.4
Requirement already satisfied (use --upgrade to upgrade): traitlets==4.2.1 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Collecting weasyprint==0.36
Collecting webencodings==0.5.1
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): wheel==0.29.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages
Installing collected packages: biopython, pycparser, cffi, cairocffi, cairosvg, cssselect, cycler, ete3, functools32, webencodings, html5lib, lxml, numpy, python-dateutil, pytz, pyparsing, subprocess32, matplotlib, pandas, pip, pyphen, pyyaml, scikit-learn, scipy, seaborn, tinycss, weasyprint
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed biopython-1.69 cairocffi-0.8.0 cairosvg-1.0.22 cffi-1.10.0 cssselect-1.0.1 cycler-0.10.0 ete3-3.0.0b35 functools32-3.2.3.post2 html5lib-0.999999999 lxml-3.7.3 matplotlib-2.0.2 numpy-1.12.1 pandas-0.16.0 pip-9.0.1 pycparser-2.17 pyparsing-2.2.0 pyphen-0.9.4 python-dateutil-2.6.0 pytz-2017.2 pyyaml-3.12 scikit-learn-0.17 scipy-0.19.0 seaborn-0.7.1 subprocess32-3.2.7 tinycss-0.4 weasyprint-0.36 webencodings-0.5.1
#
# To activate this environment, use:
# > source activate crt
#
# To deactivate an active environment, use:
# > source deactivate
#
```

pip install

```
pip install coretracker
Collecting coretracker
Requirement already satisfied: numpy>=1.8.2 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: scipy>=0.16.1 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: ete3 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: PyYAML in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Collecting psutil (from coretracker)
Requirement already satisfied: WeasyPrint in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: pandas in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: scikit-learn==0.17 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: matplotlib>=1.5.1 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: biopython>=1.65 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from coretracker)
Requirement already satisfied: cairocffi>=0.5 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: html5lib>=0.999999999 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: Pyphen>=0.8 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: lxml>=3.0 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: cssselect>=0.6 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: tinycss>=0.4 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: CairoSVG<2.0.0,>=1.0.20 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: cffi>=0.6 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from WeasyPrint->coretracker)
Requirement already satisfied: pytz>=2011k in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from pandas->coretracker)
Requirement already satisfied: python-dateutil in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from pandas->coretracker)
Requirement already satisfied: cycler>=0.10 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from matplotlib>=1.5.1->coretracker)
Requirement already satisfied: functools32 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from matplotlib>=1.5.1->coretracker)
Requirement already satisfied: six>=1.10 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from matplotlib>=1.5.1->coretracker)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from matplotlib>=1.5.1->coretracker)
Requirement already satisfied: subprocess32 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from matplotlib>=1.5.1->coretracker)
Requirement already satisfied: setuptools>=18.5 in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg (from html5lib>=0.999999999->WeasyPrint->coretracker)
Requirement already satisfied: webencodings in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from html5lib>=0.999999999->WeasyPrint->coretracker)
Requirement already satisfied: pycparser in /home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages (from cffi>=0.6->WeasyPrint->coretracker)
Installing collected packages: psutil, coretracker
Successfully installed coretracker-1.5.3 psutil-5.6.5
```

problem when calling "coretracker -h"

```
coretracker -h
Traceback (most recent call last):
  File "/home/edisudianto/anaconda/envs/crt/bin/coretracker", line 21, in <module>
    from coretracker.classifier import Classifier, read_from_json
  File "/home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages/coretracker/classifier/__init__.py", line 14, in <module>
    from classifier import Classifier, getDataFromFeatures, read_from_json
  File "/home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages/coretracker/classifier/classifier.py", line 12, in <module>
    from sklearn import cross_validation, feature_selection, preprocessing, svm
  File "/home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages/sklearn/base.py", line 11, in <module>
    from .utils.fixes import signature
  File "/home/edisudianto/anaconda/envs/crt/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
  File "numpy.pxd", line 861, in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5033)
ValueError: numpy.ufunc has the wrong size, try recompiling
```

**Comment by esud1** [comment]
Hi @maclandrol 

I managed to resolve the problems and currently trying out the tutorials. 
Many thanks for your help!
